### ISSUE TITLE
Error: GlobalKey was used multiple times - Expanded

### ISSUE THREAD

**Issue by magillus** [MaikuB/master_detail_scaffold#2]
Got error trying to use the package with similar to example usecase

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Expanded(flex: 1):
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#9dacb]
The parent of the widgets with that key was: Expanded
    flex: 1
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#9dacb]
    dirty
    state: NavigatorState#9b449(lifecycle state: created)
The second child that was to be instantiated with that key was: Expanded
```

**Comment by MaikuB** [comment]
Can you provide a link to a minimal sample app or a complete code snippet that can reproduce the problem?

**Comment by magillus** [comment]
Thank you for prompt response, I needed to work around it, I try to recreate on sample app.

for now I can provide :
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.170, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.42.1)
[√] VS Code, 32-bit edition (version 1.42.0)
[√] Connected device (3 available)
```

**Comment by MaikuB** [comment]
Afraid that info doesn't really help. There's an example app in this repository and you could fork the repository, update the example app to provide a way to reproduce the issue and post the link to it here

**Comment by magillus** [comment]
When I get a chance to give another try - I will reopen the issue, thank you.

**Comment by WouterGoossenss** [comment]
@MaikuB, I've encountered the same issue. It arises when you try to use more than one MasterDetailScaffold, e.g. with a BottomNavigationBar. Using it more than once, results in a duplicate GlobalKey. I tried to modify remove the GlobalKey from the package but had no success in doing so. Do you have any suggestions on how to fix this?

**Comment by MaikuB** [comment]
Afraid not. The code is open-sourced so should you find a solution then please submit a PR. It's possible you may need to fork and modify the package to suit your use case. Perhaps this is something could using the changes with the Navigator 2.0 work the Flutter team did that introduces a new router widget.
