### ISSUE TITLE
Multiple Details page pushed one on top of other in landscape mode

### ISSUE THREAD

**Issue by freesailor** [MaikuB/master_detail_scaffold#5]
Hi, I ran your example app, and rotate the phone to landscape to have both panes.
Then I click successively on many tiles.
Then I rotate back the phone to portrait.
The last tile detail is shown. then I click the back button and the last tile is popped, but while I expected to get the master pane, it's the previous tile that is shown.
I have to continue popping all the tiles that were clicked.
Is this the expected behavior or some this is wrong.
Thanks

**Comment by MaikuB** [comment]
Yes this is expected behaviour for the example app

**Comment by MaikuB** [comment]
Should add that navigation is left for developers to implement i.e. what you're seeing is being handled by the navigation app
